flash:
  notice: "alert-info"
  error: "alert-error"
  alert: "alert-warning"
  success: "alert-success"
  failed: "alert-danger"
user:
  username:
    random_suffix_length: 3
  first_name:
    max_length: 30
  last_name:
    max_length: 30
review:
  number_of_criteria: 5
  criteria: [
    {attr_name: rating_criterion_1, ratio: 20},
    {attr_name: rating_criterion_2, ratio: 20},
    {attr_name: rating_criterion_3, ratio: 20},
    {attr_name: rating_criterion_4, ratio: 20},
    {attr_name: rating_criterion_5, ratio: 20}
  ]
  rating_values: [1, 2, 3, 4, 5]
validations:
  review:
    title:
      max_length: 255
      min_length: 20
    content:
      max_length: 10000
      min_length: 20
  review_verification:
    email:
      max_length: 255
