flash:
  notice: "alert-info"
  error: "alert-error"
  alert: "alert-warning"
  success: "alert-success"
  failed: "alert-danger"
user:
  username:
    random_suffix_length: 3
  first_name:
    max_length: 30
  last_name:
    max_length: 30
review:
  number_of_criteria: 5
  criteria: [
    {attr_name: rating_criterion_1, ratio: 20},
    {attr_name: rating_criterion_2, ratio: 20},
    {attr_name: rating_criterion_3, ratio: 20},
    {attr_name: rating_criterion_4, ratio: 20},
    {attr_name: rating_criterion_5, ratio: 20}
  ]
  rating_values: [1, 2, 3, 4, 5]
vote:
  vote_type_point:
    up: 1
    down: -1
  display_vote_type:
    up: ▲
    down: ▼
validations:
  review:
    title:
      max_length: 255
      min_length: 20
    content:
      max_length: 10000
      min_length: 20
  review_verification:
    email:
      max_length: 255
google_map:
  src: https://maps.googleapis.com/maps/api/js
  key: AIzaSyAX6x28nsjEWmeL-10FkZZSo1yFmUfn3JU
  libraries: places
  sensor: false
  language: vi
  region: VN
  tilt: 45
  branch_info:
    icon_url: /assets/80x20.jpg
    avatar:
      height: 100px
      width: 100%
