flash:
  notice: "alert-info"
  error: "alert-error"
  alert: "alert-warning"
  success: "alert-success"
  failed: "alert-danger"
user:
  username:
    random_suffix_length: 3
  first_name:
    max_length: 30
  last_name:
    max_length: 30
